---
- name: Ruby development environment
  hosts: all

  tasks:
  - name: Add user 'vagrant' to group 'vboxsf'
    become: yes
    user:
      name: vagrant
      groups: vboxsf
      append: yes

  - name: Mount shared folder
    become: yes
    mount:
      path: /mnt/packer-mikrotik
      src: packer-mikrotik
      fstype: vboxsf
      opts: rw,exec,uid=vagrant,gid=vboxsf,dmode=775,fmode=664
      state: mounted

  roles:
    - name: Install ruby
      role: rvm.ruby
      rvm1_rubies: ['ruby-2.5.7']
      rvm1_user: 'vagrant'
